feature_net_kwargs:
  rgb_feat:
    cls: DummyImgFeat
    output_dim: 512
  compass:
    cls: CompassMLP
    input_dim: 4
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2
  gps:
    cls: GPSMLP
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2
  voxels:
    cls: FlattenedVoxelBlockEncoder
    embed_dim: 8
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2
  biome_id:
    cls: BiomeIDEmb
    embed_dim: 8
  prev_action:
    cls: PrevActionEmb
    embed_dim: 8
  prompt:
    cls: PromptEmbFeat
    output_dim: 512

feature_fusion:
  output_dim: 512
  hidden_depth: 0

actor:
  hidden_dim: 256
  hidden_depth: 3

mineclip:
  arch: "vit_base_p16_fz.v2.t2"
  hidden_dim: 512
  image_feature_dim: 512
  mlp_adapter_spec: "v0-2.t0"
  pool_type: "attn.d2.nh8.glusw"  # filled by variant
  resolution: [160, 256]
  ckpt:
    path:  /home/user/weights/attn.pth # filled by users
    checksum: "b5ece9198337cfd117a3bfbd921e56da"

hyperparameters:
  task: "dummy env"
  number_actions: 89
  epochs: 10
  PPO_buffer_size: 100000
  batch_size: 10000

  SI_buffer_size: 50
  buffer_mean: 0.1
  buffer_std: 0
  buffer_delta: 0

  video_min_rew: 30

  load_checkpoint: false
  checkpoint_dir: "/home/user/Mine/results/run_231109_0814/weights"
  checkpoint_epoch: 0

  imitation_learning: false
  demos_path: ""
  
  file_logging: true
  wandb_init: false


# hydra: 
#   job:
#     chdir: true
#   run:
#     dir: .
#   output_subdir: null